# ============================================================
# templates/serviceaccount.yaml
# PURPOSE: Kubernetes ServiceAccount for our pods
# Used by IRSA in Module 12 (Vault)
# ============================================================

{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "enterprise-platform.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "enterprise-platform.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{/*
    {{- with .Values.serviceAccount.annotations }}
    → "with" sets context to annotations map
    → only renders block if annotations is not empty
    → avoids "annotations: {}" in output
    toYaml → converts map to YAML string
    nindent 4 → indent 4 spaces with leading newline
  */}}
{{- end }}