apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: enterprise-platform
    managed-by: argocd
spec:
  project: enterprise-platform

  source:
    repoURL: https://github.com/GokulGK01/enterprise-platform.git
    targetRevision: main
    path: helm/enterprise-platform
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: enterprise-platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
