apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: enterprise-platform
  namespace: argocd
spec:
  description: Enterprise Platform Project

  sourceRepos:
    - "*"

  destinations:
    - namespace: "*"
      server: "*"

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    # Allow ALL cluster resources
    # includes argoproj.io/Application
    # Simplest fix — restrict later in production

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
    # Allow ALL namespace resources
